package com.neonomics.model;

public interface Schemas {
	
	public static final String AuthSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"object\",\r\n"
			+ "    \"required\": [\r\n"
			+ "        \"refresh_expires_in\",\r\n"
			+ "        \"expires_in\",\r\n"
			+ "        \"session_state\",\r\n"
			+ "        \"access_token\",\r\n"
			+ "        \"scope\",\r\n"
			+ "        \"token_type\",\r\n"
			+ "        \"refresh_token\"\r\n"
			+ "    ],\r\n"
			+ "    \"properties\": {\r\n"
			+ "        \"refresh_expires_in\": {\r\n"
			+ "            \"$id\": \"#/properties/refresh_expires_in\",\r\n"
			+ "            \"type\": \"integer\"\r\n"
			+ "        },\r\n"
			+ "        \"expires_in\": {\r\n"
			+ "            \"$id\": \"#/properties/expires_in\",\r\n"
			+ "            \"type\": \"integer\"\r\n"
			+ "        },\r\n"
			+ "        \"session_state\": {\r\n"
			+ "            \"$id\": \"#/properties/session_state\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"access_token\": {\r\n"
			+ "            \"$id\": \"#/properties/access_token\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"scope\": {\r\n"
			+ "            \"$id\": \"#/properties/scope\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"token_type\": {\r\n"
			+ "            \"$id\": \"#/properties/token_type\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"refresh_token\": {\r\n"
			+ "            \"$id\": \"#/properties/refresh_token\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String BanksSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"array\",\r\n"
			+ "    \"items\": {\r\n"
			+ "        \"$id\": \"#/items\",\r\n"
			+ "        \"type\": \"object\",\r\n"
			+ "        \"required\": [\r\n"
			+ "            \"countryCode\",\r\n"
			+ "            \"bankingGroupName\",\r\n"
			+ "            \"personalIdentificationRequired\",\r\n"
			+ "            \"id\",\r\n"
			+ "            \"bankDisplayName\",\r\n"
			+ "            \"supportedServices\",\r\n"
			+ "            \"bic\",\r\n"
			+ "            \"bankOfficialName\",\r\n"
			+ "            \"status\"\r\n"
			+ "        ],\r\n"
			+ "        \"properties\": {\r\n"
			+ "            \"countryCode\": {\r\n"
			+ "                \"$id\": \"#/items/properties/countryCode\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"bankingGroupName\": {\r\n"
			+ "                \"$id\": \"#/items/properties/bankingGroupName\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"personalIdentificationRequired\": {\r\n"
			+ "                \"$id\": \"#/items/properties/personalIdentificationRequired\",\r\n"
			+ "                \"type\": \"boolean\"\r\n"
			+ "            },\r\n"
			+ "            \"id\": {\r\n"
			+ "                \"$id\": \"#/items/properties/id\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"bankDisplayName\": {\r\n"
			+ "                \"$id\": \"#/items/properties/bankDisplayName\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"supportedServices\": {\r\n"
			+ "                \"$id\": \"#/items/properties/supportedServices\",\r\n"
			+ "                \"type\": \"array\",\r\n"
			+ "                \"items\": {\r\n"
			+ "                    \"$id\": \"#/items/properties/supportedServices/items\",\r\n"
			+ "                    \"type\": \"string\"\r\n"
			+ "                }\r\n"
			+ "            },\r\n"
			+ "            \"bic\": {\r\n"
			+ "                \"$id\": \"#/items/properties/bic\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"bankOfficialName\": {\r\n"
			+ "                \"$id\": \"#/items/properties/bankOfficialName\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"status\": {\r\n"
			+ "                \"$id\": \"#/items/properties/status\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String SessionIdSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"object\",\r\n"
			+ "    \"required\": [\r\n"
			+ "        \"sessionId\"\r\n"
			+ "    ],\r\n"
			+ "    \"properties\": {\r\n"
			+ "        \"sessionId\": {\r\n"
			+ "            \"$id\": \"#/properties/sessionId\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String SessionStatusSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"object\",\r\n"
			+ "    \"examples\": [\r\n"
			+ "        {\r\n"
			+ "            \"bankId\": \"aGl6b250aWJhbmsudjFISVpPTk9LSw==\",\r\n"
			+ "            \"bankName\": \"Justo Bank\",\r\n"
			+ "            \"createdAt\": \"Fri Aug 02 14:49:26 CEST 2019\",\r\n"
			+ "            \"providerId\": \"justobank.v1\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"required\": [\r\n"
			+ "        \"bankId\",\r\n"
			+ "        \"bankName\",\r\n"
			+ "        \"createdAt\",\r\n"
			+ "        \"providerId\"\r\n"
			+ "    ],\r\n"
			+ "    \"properties\": {\r\n"
			+ "        \"bankId\": {\r\n"
			+ "            \"$id\": \"#/properties/bankId\",\r\n"
			+ "            \"type\": \"string\",\r\n"
			+ "            \"examples\": [\r\n"
			+ "                \"aGl6b250aWJhbmsudjFISVpPTk9LSw==\"\r\n"
			+ "            ]\r\n"
			+ "        },\r\n"
			+ "        \"bankName\": {\r\n"
			+ "            \"$id\": \"#/properties/bankName\",\r\n"
			+ "            \"type\": \"string\",\r\n"
			+ "            \"examples\": [\r\n"
			+ "                \"Justo Bank\"\r\n"
			+ "            ]\r\n"
			+ "        },\r\n"
			+ "        \"createdAt\": {\r\n"
			+ "            \"$id\": \"#/properties/createdAt\",\r\n"
			+ "            \"type\": \"string\",\r\n"
			+ "            \"examples\": [\r\n"
			+ "                \"Fri Aug 02 14:49:26 CEST 2019\"\r\n"
			+ "            ]\r\n"
			+ "        },\r\n"
			+ "        \"providerId\": {\r\n"
			+ "            \"$id\": \"#/properties/providerId\",\r\n"
			+ "            \"type\": \"string\",\r\n"
			+ "            \"examples\": [\r\n"
			+ "                \"justobank.v1\"\r\n"
			+ "            ]\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String AllAccountsSchema = "{\r\n"

			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"array\",\r\n"
			+ "    \"additionalItems\": true,\r\n"
			+ "    \"items\": {\r\n"
			+ "        \"$id\": \"#/items\",\r\n"
			+ "        \"anyOf\": [\r\n"
			+ "            {\r\n"
			+ "                \"$id\": \"#/items/anyOf/0\",\r\n"
			+ "                \"type\": \"object\",\r\n"
			+ "                \"required\": [\r\n"
			+ "                    \"id\",\r\n"
			+ "                    \"bban\",\r\n"
			+ "                    \"iban\",\r\n"
			+ "                    \"accountName\",\r\n"
			+ "                    \"accountType\",\r\n"
			+ "                    \"balances\"\r\n"
			+ "                ],\r\n"
			+ "                \"properties\": {\r\n"
			+ "                    \"id\": {\r\n"
			+ "                        \"$id\": \"#/items/anyOf/0/properties/id\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"bban\": {\r\n"
			+ "                        \"$id\": \"#/items/anyOf/0/properties/bban\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"iban\": {\r\n"
			+ "                        \"$id\": \"#/items/anyOf/0/properties/iban\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"accountName\": {\r\n"
			+ "                        \"$id\": \"#/items/anyOf/0/properties/accountName\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"accountType\": {\r\n"
			+ "                        \"$id\": \"#/items/anyOf/0/properties/accountType\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"balances\": {\r\n"
			+ "                        \"$id\": \"#/items/anyOf/0/properties/balances\",\r\n"
			+ "                        \"type\": \"array\",\r\n"
			+ "                        \"additionalItems\": true,\r\n"
			+ "                        \"items\": {\r\n"
			+ "                            \"$id\": \"#/items/anyOf/0/properties/balances/items\",\r\n"
			+ "                            \"anyOf\": [\r\n"
			+ "                                {\r\n"
			+ "                                    \"$id\": \"#/items/anyOf/0/properties/balances/items/anyOf/0\",\r\n"
			+ "                                    \"type\": \"object\",\r\n"
			+ "                                    \"required\": [\r\n"
			+ "                                        \"amount\",\r\n"
			+ "                                        \"currency\",\r\n"
			+ "                                        \"type\"\r\n"
			+ "                                    ],\r\n"
			+ "                                    \"properties\": {\r\n"
			+ "                                        \"amount\": {\r\n"
			+ "                                            \"$id\": \"#/items/anyOf/0/properties/balances/items/anyOf/0/properties/amount\",\r\n"
			+ "                                            \"type\": \"string\"\r\n"
			+ "                                        },\r\n"
			+ "                                        \"currency\": {\r\n"
			+ "                                            \"$id\": \"#/items/anyOf/0/properties/balances/items/anyOf/0/properties/currency\",\r\n"
			+ "                                            \"type\": \"string\"\r\n"
			+ "                                        },\r\n"
			+ "                                        \"type\": {\r\n"
			+ "                                            \"$id\": \"#/items/anyOf/0/properties/balances/items/anyOf/0/properties/type\",\r\n"
			+ "                                            \"type\": \"string\"\r\n"
			+ "                                        }\r\n"
			+ "                                    },\r\n"
			+ "                                    \"additionalProperties\": true\r\n"
			+ "                                }\r\n"
			+ "                            ]\r\n"
			+ "                        }\r\n"
			+ "                    }\r\n"
			+ "                },\r\n"
			+ "                \"additionalProperties\": true\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    }\r\n"
			+ "}";

	public static final String ConsentResponseSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"object\",\r\n"
			+ "    \"required\": [\r\n"
			+ "        \"message\",\r\n"
			+ "        \"links\"\r\n"
			+ "    ],\r\n"
			+ "    \"properties\": {\r\n"
			+ "        \"message\": {\r\n"
			+ "            \"$id\": \"#/properties/message\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"links\": {\r\n"
			+ "            \"$id\": \"#/properties/links\",\r\n"
			+ "            \"type\": \"array\",\r\n"
			+ "            \"items\": {\r\n"
			+ "                \"$id\": \"#/properties/links/items\",\r\n"
			+ "                \"type\": \"object\",\r\n"
			+ "                \"required\": [\r\n"
			+ "                    \"type\",\r\n"
			+ "                    \"rel\",\r\n"
			+ "                    \"href\"\r\n"
			+ "                ],\r\n"
			+ "                \"properties\": {\r\n"
			+ "                    \"type\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/type\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"rel\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/rel\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"href\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/href\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ConsentRequiredSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"object\",\r\n"
			+ "    \"required\": [\r\n"
			+ "        \"id\",\r\n"
			+ "        \"errorCode\",\r\n"
			+ "        \"message\",\r\n"
			+ "        \"source\",\r\n"
			+ "        \"type\",\r\n"
			+ "        \"timestamp\",\r\n"
			+ "        \"links\"\r\n"
			+ "    ],\r\n"
			+ "    \"properties\": {\r\n"
			+ "        \"id\": {\r\n"
			+ "            \"$id\": \"#/properties/id\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"errorCode\": {\r\n"
			+ "            \"$id\": \"#/properties/errorCode\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"message\": {\r\n"
			+ "            \"$id\": \"#/properties/message\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"source\": {\r\n"
			+ "            \"$id\": \"#/properties/source\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"type\": {\r\n"
			+ "            \"$id\": \"#/properties/type\",\r\n"
			+ "            \"type\": \"string\"\r\n"
			+ "        },\r\n"
			+ "        \"timestamp\": {\r\n"
			+ "            \"$id\": \"#/properties/timestamp\",\r\n"
			+ "            \"type\": \"number\"\r\n"
			+ "        },\r\n"
			+ "        \"links\": {\r\n"
			+ "            \"$id\": \"#/properties/links\",\r\n"
			+ "            \"type\": \"array\",\r\n"
			+ "            \"items\": {\r\n"
			+ "                \"$id\": \"#/properties/links/items\",\r\n"
			+ "                \"type\": \"object\",\r\n"
			+ "                \"required\": [\r\n"
			+ "                    \"type\",\r\n"
			+ "                    \"rel\",\r\n"
			+ "                    \"href\",\r\n"
			+ "                    \"meta\"\r\n"
			+ "                ],\r\n"
			+ "                \"properties\": {\r\n"
			+ "                    \"type\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/type\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"rel\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/rel\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"href\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/href\",\r\n"
			+ "                        \"type\": \"string\"\r\n"
			+ "                    },\r\n"
			+ "                    \"meta\": {\r\n"
			+ "                        \"$id\": \"#/properties/links/items/properties/meta\",\r\n"
			+ "                        \"type\": \"object\",\r\n"
			+ "                        \"required\": [\r\n"
			+ "                            \"id\"\r\n"
			+ "                        ],\r\n"
			+ "                        \"properties\": {\r\n"
			+ "                            \"id\": {\r\n"
			+ "                                \"$id\": \"#/properties/links/items/properties/meta/properties/id\",\r\n"
			+ "                                \"type\": \"string\"\r\n"
			+ "                            }\r\n"
			+ "                        }\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";

	public static final String AccountDataSchema = "{\r\n"
			+ "    \"$schema\": \"http://json-schema.org/draft-07/schema\",\r\n"
			+ "    \"$id\": \"http://example.com/example.json\",\r\n"
			+ "    \"type\": \"array\",\r\n"
			+ "    \"items\": {\r\n"
			+ "        \"$id\": \"#/items\",\r\n"
			+ "        \"type\": \"object\",\r\n"
			+ "        \"required\": [\r\n"
			+ "            \"id\",\r\n"
			+ "            \"iban\",\r\n"
			+ "            \"bban\",\r\n"
			+ "            \"accountName\",\r\n"
			+ "            \"accountType\",\r\n"
			+ "            \"balances\"\r\n"
			+ "        ],\r\n"
			+ "        \"properties\": {\r\n"
			+ "            \"id\": {\r\n"
			+ "                \"$id\": \"#/items/properties/id\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"iban\": {\r\n"
			+ "                \"$id\": \"#/items/properties/iban\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"bban\": {\r\n"
			+ "                \"$id\": \"#/items/properties/bban\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountName\": {\r\n"
			+ "                \"$id\": \"#/items/properties/accountName\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"accountType\": {\r\n"
			+ "                \"$id\": \"#/items/properties/accountType\",\r\n"
			+ "                \"type\": \"string\"\r\n"
			+ "            },\r\n"
			+ "            \"balances\": {\r\n"
			+ "                \"$id\": \"#/items/properties/balances\",\r\n"
			+ "                \"type\": \"array\",\r\n"
			+ "                \"items\": {\r\n"
			+ "                    \"$id\": \"#/items/properties/balances/items\",\r\n"
			+ "                    \"type\": \"object\",\r\n"
			+ "                    \"required\": [\r\n"
			+ "                        \"amount\",\r\n"
			+ "                        \"currency\",\r\n"
			+ "                        \"type\"\r\n"
			+ "                    ],\r\n"
			+ "                    \"properties\": {\r\n"
			+ "                        \"amount\": {\r\n"
			+ "                            \"$id\": \"#/items/properties/balances/items/properties/amount\",\r\n"
			+ "                            \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"currency\": {\r\n"
			+ "                            \"$id\": \"#/items/properties/balances/items/properties/currency\",\r\n"
			+ "                            \"type\": \"string\"\r\n"
			+ "                        },\r\n"
			+ "                        \"type\": {\r\n"
			+ "                            \"$id\": \"#/items/properties/balances/items/properties/type\",\r\n"
			+ "                            \"type\": \"string\"\r\n"
			+ "                        }\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            }\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";


}
